version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5500 app:app"
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=Division
      - FLASK_APP=app.py

  tests:
    build: .
    command: ["python3", "-m", "unittest", "discover", "-s", "tests"]
    volumes:
      - .:/app