version: '3.12'
services:
  web:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=Division

  tests:
    build: .
    command: ["python3", "-m", "unittest", "discover", "-s", "tests"]
    volumes:
      - .:/app