"""empty message

Revision ID: 025d1e0d8fa1
Revises: e0735fdcbd13
Create Date: 2024-07-04 18:59:50.615481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025d1e0d8fa1'
down_revision = 'e0735fdcbd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divide')
    # ### end Alembic commands ###
